// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pb/FileService/FileService.proto

package FileService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_pb_FileService_FileService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FileService_FileService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_pb_FileService_FileService_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_pb_FileService_FileService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FileService_FileService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_pb_FileService_FileService_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_pb_FileService_FileService_proto protoreflect.FileDescriptor

const file_pb_FileService_FileService_proto_rawDesc = "" +
	"\n" +
	" pb/FileService/FileService.proto\x12\vFileService\"*\n" +
	"\vFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"$\n" +
	"\fFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2S\n" +
	"\n" +
	"FileSystem\x12E\n" +
	"\fDownloadFile\x12\x18.FileService.FileRequest\x1a\x19.FileService.FileResponse0\x01B\x12Z\x10./pb/FileServiceb\x06proto3"

var (
	file_pb_FileService_FileService_proto_rawDescOnce sync.Once
	file_pb_FileService_FileService_proto_rawDescData []byte
)

func file_pb_FileService_FileService_proto_rawDescGZIP() []byte {
	file_pb_FileService_FileService_proto_rawDescOnce.Do(func() {
		file_pb_FileService_FileService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_FileService_FileService_proto_rawDesc), len(file_pb_FileService_FileService_proto_rawDesc)))
	})
	return file_pb_FileService_FileService_proto_rawDescData
}

var file_pb_FileService_FileService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_FileService_FileService_proto_goTypes = []any{
	(*FileRequest)(nil),  // 0: FileService.FileRequest
	(*FileResponse)(nil), // 1: FileService.FileResponse
}
var file_pb_FileService_FileService_proto_depIdxs = []int32{
	0, // 0: FileService.FileSystem.DownloadFile:input_type -> FileService.FileRequest
	1, // 1: FileService.FileSystem.DownloadFile:output_type -> FileService.FileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_FileService_FileService_proto_init() }
func file_pb_FileService_FileService_proto_init() {
	if File_pb_FileService_FileService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_FileService_FileService_proto_rawDesc), len(file_pb_FileService_FileService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_FileService_FileService_proto_goTypes,
		DependencyIndexes: file_pb_FileService_FileService_proto_depIdxs,
		MessageInfos:      file_pb_FileService_FileService_proto_msgTypes,
	}.Build()
	File_pb_FileService_FileService_proto = out.File
	file_pb_FileService_FileService_proto_goTypes = nil
	file_pb_FileService_FileService_proto_depIdxs = nil
}
