== Overview & Environment
This section details the containerization of the Go-based HTTP service using Docker and its deployment within an isolated Virtual Machine. The primary objective is to establish and verify seamless network connectivity from the Host machine to the container running inside the Guest VM.

The containerized service was explicitly deployed, executed, and tested on *VirtualBox running Ubuntu 2026* as the Guest Operating System.

== Network Setup: Port Forwarding
To bridge the gap between the Host machine and the Guest VM, the VirtualBox network adapter was configured to *NAT* with *Port Forwarding*.

This specific network topology ensures that TCP traffic directed to the Host machine on port `8080` is automatically intercepted by the hypervisor, routed into the Ubuntu 2026 VM's internal network, and delivered directly to the exposed Docker container running on port `8080`. This architecture allows seamless API testing from the Host using `localhost:8080`.
== Execution Instructions
To build and deploy the service, the following commands must be executed within the Guest VM's terminal in the directory containing the `Dockerfile`.

=== Build the Docker Image:
This command packages the Go application and its required environment into a lightweight container image.

```bash
docker build -t ds-hw1-part3 .
```

=== Run the Container:
This command executes the container in the background (detached mode) and maps the exposed port to the Guest VM, preparing it to receive forwarded traffic from the Host.
```bash
docker run -d -p 8080:8080 --name calc-service ds-hw1-part3]
```

== Observability: Logging Middleware
To ensure the service is highly observable within the containerized environment, a custom HTTP logging middleware was implemented using Go's native `log/slog` package.

This middleware intercepts all incoming HTTP traffic before it reaches the core application logic, generating structured JSON logs. These logs capture critical telemetry for every request, including:
- HTTP Method (e.g., GET)
- Request Path (e.g., /compute)
- Client IP Address
- Total Processing Duration

Because these logs are structured and output to standard output (`stdout`), they are automatically captured by the Docker daemon and can be efficiently monitored and queried directly from the VM environment.

== Proof of Connectivity
The following visual evidence demonstrates successful communication from the Host machine to the containerized service operating inside the VirtualBox VM.

#v(1cm)

#figure(
  image("img/guest_build.png"),
  caption:
    "Terminal Output - Docker Image Build: Execution of the `docker build` command within the Guest VM to package the Go HTTP service into a container image."

)

#figure(
  image("img/guest_run.png"),
  caption:
    "Terminal Output - Container Execution: Starting the Docker container in detached mode within the Guest VM and mapping port 8080 to expose the service."

)

#figure(
  image("img/guest_compute.png"),
  caption:
    "Terminal Output - Guest Local Test: A successful `curl` request made locally from within the Guest VM, verifying that the containerized service is responding correctly before testing Host connectivity."

)

#figure(
  image("img/add.png"),
  caption:
    "Terminal Output - Host Requesting Addition: Successful Host-to-VM connectivity demonstration. The Host machine requests the `/compute` endpoint with `op=add`, and the containerized service returns the correctly calculated JSON result."

)

#figure(
  image("img/div_zero.png"),
  caption:
    "Terminal Output - Division by Zero Handling: Demonstration of the service's internal error management. A request attempting to divide by zero is intercepted, returning a structured JSON error message and the appropriate HTTP status code."

)

#figure(
  image("img/host_post.png"),
  caption:
    "Terminal Output - Invalid HTTP Method Request: A `curl` request initiated from the Host machine using an unsupported `POST` method to test the API's routing constraints."

)

#figure(
  image("img/missing_op.png"),
  caption:
    "Terminal Output - Missing Parameter Error: The service successfully validates incoming queries and returns an HTTP 400 Bad Request error when the required  parameter is omitted."

)

#figure(
  image("img/guest_logs.png"),
  caption:
    "Terminal Output - Middleware Logs: Viewing the container logs via `docker logs`. This displays the structured JSON output generated by the custom logging middleware, capturing request methods, paths, and total processing durations."
)