// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pb/AuthService/AuthService.proto

package AuthService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_UNDEFINED UserRole = 0
	UserRole_USER      UserRole = 1
	UserRole_ADMIN     UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UNDEFINED",
		1: "USER",
		2: "ADMIN",
	}
	UserRole_value = map[string]int32{
		"UNDEFINED": 0,
		"USER":      1,
		"ADMIN":     2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_AuthService_AuthService_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_pb_AuthService_AuthService_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_pb_AuthService_AuthService_proto_rawDescGZIP(), []int{0}
}

type ReqAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAuth) Reset() {
	*x = ReqAuth{}
	mi := &file_pb_AuthService_AuthService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuth) ProtoMessage() {}

func (x *ReqAuth) ProtoReflect() protoreflect.Message {
	mi := &file_pb_AuthService_AuthService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuth.ProtoReflect.Descriptor instead.
func (*ReqAuth) Descriptor() ([]byte, []int) {
	return file_pb_AuthService_AuthService_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role          UserRole               `protobuf:"varint,2,opt,name=role,proto3,enum=AuthService.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResAuth) Reset() {
	*x = ResAuth{}
	mi := &file_pb_AuthService_AuthService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResAuth) ProtoMessage() {}

func (x *ResAuth) ProtoReflect() protoreflect.Message {
	mi := &file_pb_AuthService_AuthService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResAuth.ProtoReflect.Descriptor instead.
func (*ResAuth) Descriptor() ([]byte, []int) {
	return file_pb_AuthService_AuthService_proto_rawDescGZIP(), []int{1}
}

func (x *ResAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResAuth) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNDEFINED
}

var File_pb_AuthService_AuthService_proto protoreflect.FileDescriptor

const file_pb_AuthService_AuthService_proto_rawDesc = "" +
	"\n" +
	" pb/AuthService/AuthService.proto\x12\vAuthService\"A\n" +
	"\aReqAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\aResAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.AuthService.UserRoleR\x04role*.\n" +
	"\bUserRole\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x022A\n" +
	"\n" +
	"AuthSystem\x123\n" +
	"\x05Login\x12\x14.AuthService.ReqAuth\x1a\x14.AuthService.ResAuthB\x12Z\x10./pb/AuthServiceb\x06proto3"

var (
	file_pb_AuthService_AuthService_proto_rawDescOnce sync.Once
	file_pb_AuthService_AuthService_proto_rawDescData []byte
)

func file_pb_AuthService_AuthService_proto_rawDescGZIP() []byte {
	file_pb_AuthService_AuthService_proto_rawDescOnce.Do(func() {
		file_pb_AuthService_AuthService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_AuthService_AuthService_proto_rawDesc), len(file_pb_AuthService_AuthService_proto_rawDesc)))
	})
	return file_pb_AuthService_AuthService_proto_rawDescData
}

var file_pb_AuthService_AuthService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_AuthService_AuthService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_AuthService_AuthService_proto_goTypes = []any{
	(UserRole)(0),   // 0: AuthService.UserRole
	(*ReqAuth)(nil), // 1: AuthService.ReqAuth
	(*ResAuth)(nil), // 2: AuthService.ResAuth
}
var file_pb_AuthService_AuthService_proto_depIdxs = []int32{
	0, // 0: AuthService.ResAuth.role:type_name -> AuthService.UserRole
	1, // 1: AuthService.AuthSystem.Login:input_type -> AuthService.ReqAuth
	2, // 2: AuthService.AuthSystem.Login:output_type -> AuthService.ResAuth
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_AuthService_AuthService_proto_init() }
func file_pb_AuthService_AuthService_proto_init() {
	if File_pb_AuthService_AuthService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_AuthService_AuthService_proto_rawDesc), len(file_pb_AuthService_AuthService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_AuthService_AuthService_proto_goTypes,
		DependencyIndexes: file_pb_AuthService_AuthService_proto_depIdxs,
		EnumInfos:         file_pb_AuthService_AuthService_proto_enumTypes,
		MessageInfos:      file_pb_AuthService_AuthService_proto_msgTypes,
	}.Build()
	File_pb_AuthService_AuthService_proto = out.File
	file_pb_AuthService_AuthService_proto_goTypes = nil
	file_pb_AuthService_AuthService_proto_depIdxs = nil
}
