// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: pb/AuthService/AuthService.proto

package AuthService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthSystem_Login_FullMethodName = "/AuthService.AuthSystem/Login"
)

// AuthSystemClient is the client API for AuthSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSystemClient interface {
	Login(ctx context.Context, in *ReqAuth, opts ...grpc.CallOption) (*ResAuth, error)
}

type authSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSystemClient(cc grpc.ClientConnInterface) AuthSystemClient {
	return &authSystemClient{cc}
}

func (c *authSystemClient) Login(ctx context.Context, in *ReqAuth, opts ...grpc.CallOption) (*ResAuth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResAuth)
	err := c.cc.Invoke(ctx, AuthSystem_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSystemServer is the server API for AuthSystem service.
// All implementations must embed UnimplementedAuthSystemServer
// for forward compatibility.
type AuthSystemServer interface {
	Login(context.Context, *ReqAuth) (*ResAuth, error)
	mustEmbedUnimplementedAuthSystemServer()
}

// UnimplementedAuthSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthSystemServer struct{}

func (UnimplementedAuthSystemServer) Login(context.Context, *ReqAuth) (*ResAuth, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthSystemServer) mustEmbedUnimplementedAuthSystemServer() {}
func (UnimplementedAuthSystemServer) testEmbeddedByValue()                    {}

// UnsafeAuthSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSystemServer will
// result in compilation errors.
type UnsafeAuthSystemServer interface {
	mustEmbedUnimplementedAuthSystemServer()
}

func RegisterAuthSystemServer(s grpc.ServiceRegistrar, srv AuthSystemServer) {
	// If the following call panics, it indicates UnimplementedAuthSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthSystem_ServiceDesc, srv)
}

func _AuthSystem_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSystemServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSystem_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSystemServer).Login(ctx, req.(*ReqAuth))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSystem_ServiceDesc is the grpc.ServiceDesc for AuthSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService.AuthSystem",
	HandlerType: (*AuthSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthSystem_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/AuthService/AuthService.proto",
}
